---
- name: Install Docker
  hosts: all
  become: yes

  tasks:
    - name: Install lvm2
      yum:
        name: lvm2
        state: latest

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
  

    - name: Install Docker
      package:
        name: docker-ce
        state: latest
     
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
    - name: récuper l'image de docker hube
      shell: sudo docker pull taousdechache/myapplicationjarr:latest

    - name: deploy tomcat  docker container
      docker_container:
        image: myapplicationjarr
        name:  myappjar        
        state: started
        auto_remove: true
        ports:
          - "888:8686"
 

